from fastapi import FastAPI, Query
from pydantic import BaseModel
from typing import Optional
from fastapi.staticfiles import StaticFiles
from fastapi.responses import FileResponse
from fastapi import HTTPException
import os
import sys
import json
from pathlib import Path


BASE_RESULTS_DIR = Path("/home/kali/autorecon-results")
RESULTS_BASE = os.path.expanduser("~/autorecon-results")
CURRENT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.dirname(CURRENT_DIR)
if PROJECT_ROOT not in sys.path:
    sys.path.append(PROJECT_ROOT)

from ai_agent import handle_message  # core brain
from recon_api import read_progress



app = FastAPI(
    title="B-Recon AI API",
    description="HTTP API for Benny's B-Recon AI assistant (Auto-Recon integration).",
    version="1.0.0",
)


class AskRequest(BaseModel):
    question: str


class AskResponse(BaseModel):
    answer: str


@app.get("/health")
def health_check():
    """
    Simple health check endpoint.
    """
    return {"status": "ok", "message": "B-Recon API is running"}


@app.get("/ai", response_model=AskResponse)
def ask_ai_get(
    question: str = Query(..., description="User question for the Recon AI")
):
    """
    GET endpoint: /ai?question=...
    Useful for quick tests from browser or curl.
    """
    try:
        raw_answer = handle_message(question)
    except Exception as e:
        raw_answer = f"[Internal error while handling message: {e}]"

    # Ensure we ALWAYS return a string (never None)
    if raw_answer is None:
        answer_str = "[No answer was generated by B-Recon]"
    else:
        answer_str = str(raw_answer)

    return AskResponse(answer=answer_str)


@app.post("/ai", response_model=AskResponse)
def ask_ai_post(req: AskRequest):
    """
    POST endpoint: /ai
    Body: { "question": "..." }
    """
    try:
        raw_answer = handle_message(req.question)
    except Exception as e:
        raw_answer = f"[Internal error while handling message: {e}]"

    if raw_answer is None:
        answer_str = "[No answer was generated by B-Recon]"
    else:
        answer_str = str(raw_answer)

    return AskResponse(answer=answer_str)

@app.get("/progress")

def get_progress(domain: str):
    """
    Return current progress log lines for a given domain.
    Example: /progress?domain=google.com
    """
    lines = read_progress(domain)
    return {"domain": domain, "lines": lines}


@app.get("/report/technical")
def download_technical_report(domain: str):
    """
    Download the technical report (Markdown) as a .txt file.
    Example:
    /report/technical?domain=tesla.com
    """
    domain_dir = os.path.join(RESULTS_BASE, domain)
    report_path = os.path.join(domain_dir, "report.md")

    if not os.path.exists(report_path):
        raise HTTPException(status_code=404, detail="Technical report not found for this domain")

    download_name = f"{domain}_technical_report.txt"
    return FileResponse(
        report_path,
        media_type="text/plain",
        filename=download_name,
    )

@app.get("/report/human")
def download_human_summary(domain: str):
    """
    Download the human-readable executive summary as a .txt file.
    Example:
    /report/human?domain=tesla.com
    """
    domain_dir = os.path.join(RESULTS_BASE, domain)
    summary_path = os.path.join(domain_dir, "executive_summary.txt")

    if not os.path.exists(summary_path):
        raise HTTPException(status_code=404, detail="Human summary not found for this domain")

    download_name = f"{domain}_human_summary.txt"
    return FileResponse(
        summary_path,
        media_type="text/plain",
        filename=download_name,
    )

@app.get("/reports/technical")
def get_technical_report(domain: str):
    report_path = BASE_RESULTS_DIR / domain / "report.md"
    if not report_path.exists():
        raise HTTPException(status_code=404, detail="Technical report not found")
    return FileResponse(
        report_path,
        media_type="text/markdown",
        filename=f"{domain}_technical_report.md",
    )


@app.get("/reports/human")
def get_human_summary(domain: str):
    summary_path = BASE_RESULTS_DIR / domain / "executive_summary.txt"
    if not summary_path.exists():
        raise HTTPException(status_code=404, detail="Human summary not found")
    return FileResponse(
        summary_path,
        media_type="text/plain",
        filename=f"{domain}_human_summary.txt",
    )


app.mount("/chat", StaticFiles(directory="web", html=True), name="chat")
